---
include:
  - board: eyelash_corne_left
    shield: nice_view_gem
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view_gem
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left_studio
    shield: nice_view_gem
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
 
