---
include:
  - board: nice_nano_v2
    shield: kyria_left nice_view_adapter nice_view_gem
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: nice_nano_v2
    shield: kyria_right nice_view_adapter nice_view_gem
    #snippet: zmk-usb-logging
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
 
